/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.SanPham;

import Validate.Validate;
import entity.Thuoctinh;
import java.awt.Color;
import service.ThuocTinh_Service;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hieul
 */
public class ThuocTinh extends javax.swing.JFrame {

    ThuocTinh_Service tts = new ThuocTinh_Service();
    public static int t;
    Validate v = new Validate();

    /**
     * Creates new form ThuocTinh
     */
    public ThuocTinh() {
        initComponents();
        loadDataColor(tts.getList_Mau());
        loadDataDanhMuc(tts.getList_DanhMuc());
        loadDataSize(tts.getList_Size());
        setLocationRelativeTo(null);
    }

    public void loadDataColor(ArrayList<Thuoctinh> ListMau) {
        DefaultTableModel model = (DefaultTableModel) tblThuocTinh.getModel();
        model.setRowCount(0);
        for (Thuoctinh tte : ListMau) {
            model.addRow(new Object[]{
                tte.getMaThuocTinh(),
                tte.getTenThuocTinh()
            });
        }
    }

    public void loadDataSize(ArrayList<Thuoctinh> ListSize) {
        DefaultTableModel model = (DefaultTableModel) tblThuocTinh.getModel();
        model.setRowCount(0);
        for (Thuoctinh tte : ListSize) {
            model.addRow(new Object[]{
                tte.getMaThuocTinh(),
                tte.getTenThuocTinh()
            });
        }
    }

    public void loadDataDanhMuc(ArrayList<Thuoctinh> ListDanhMuc) {
        DefaultTableModel model = (DefaultTableModel) tblThuocTinh.getModel();
        model.setRowCount(0);
        for (Thuoctinh tte : ListDanhMuc) {
            model.addRow(new Object[]{
                tte.getMaThuocTinh(),
                tte.getTenThuocTinh()
            });
        }
    }

    public Thuoctinh getModel() {
        Thuoctinh tte = new Thuoctinh();
        tte.setTenThuocTinh(txtThuocTinh.getText());
        return tte;
    }

    public void New() {
        txtThuocTinh.setText("");
        resetColor();
    }

    public void resetColor() {
        txtThuocTinh.setBackground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        txtThuocTinh = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThuocTinh = new javax.swing.JTable();
        btn_Them = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jButton2.setText("Return");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        tblThuocTinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Thuộc Tính", "Tên Thuộc Tính"
            }
        ));
        jScrollPane1.setViewportView(tblThuocTinh);

        btn_Them.setText("Add");
        btn_Them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemMouseClicked(evt);
            }
        });
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Update.setText("Update");
        btn_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_UpdateMouseClicked(evt);
            }
        });

        btn_Delete.setText("Delete");
        btn_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DeleteMouseClicked(evt);
            }
        });

        jLabel1.setText("Tên Thuộc Tính");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 506, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(83, 83, 83))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(3, 3, 3)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(83, 83, 83))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_Them)
                            .addGap(18, 18, 18)
                            .addComponent(btn_Update)
                            .addGap(18, 18, 18)
                            .addComponent(btn_Delete)
                            .addGap(123, 123, 123))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void btn_ThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMouseClicked

        if (t == 1) {
            StringBuilder stb = new StringBuilder();
            if (!v.isEmpty(txtThuocTinh, "Vui long nhap ten thuoc tinh muon them", stb)) {
                JOptionPane.showMessageDialog(this, stb);
            } else {
                int confirmResult = JOptionPane.showConfirmDialog(this, "Ban co chac chan muon them khong?", "Xac nhan", JOptionPane.YES_NO_OPTION);
                if (confirmResult == JOptionPane.YES_OPTION) {
                    String kq = tts.AddNew_DanhMuc(getModel());
                    JOptionPane.showMessageDialog(this, kq);
                    loadDataDanhMuc(tts.getList_DanhMuc());
                    resetColor();
                } else if (confirmResult == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(this, "Ban da huy bo them moi");
                }

            }
        }

        if (t == 2) {
            StringBuilder stb = new StringBuilder();
            if (!v.isEmpty(txtThuocTinh, "Vui long nhap ten thuoc tinh muon them", stb)) {
                JOptionPane.showMessageDialog(this, stb);
            } else {
                int confirmResult = JOptionPane.showConfirmDialog(this, "Ban co chac chan muon them khong?", "Xac nhan", JOptionPane.YES_NO_OPTION);
                if (confirmResult == JOptionPane.YES_OPTION) {
                    String kq = tts.AddNew_Mau(getModel());
                    JOptionPane.showMessageDialog(this, kq);
                    loadDataColor(tts.getList_Mau());
                    resetColor();
                } else if (confirmResult == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(this, "Ban da huy bo them moi");
                }

            }
        }

        if (t == 3) {
            StringBuilder stb = new StringBuilder();
            if (!v.isEmpty(txtThuocTinh, "Vui long nhap ten thuoc tinh muon them", stb)) {
                JOptionPane.showMessageDialog(this, stb);
            } else {
                int confirmResult = JOptionPane.showConfirmDialog(this, "Ban co chac chan muon them khong?", "Xac nhan", JOptionPane.YES_NO_OPTION);
                if (confirmResult == JOptionPane.YES_OPTION) {
                    String kq = tts.AddNew_Size(getModel());
                    JOptionPane.showMessageDialog(this, kq);
                    loadDataSize(tts.getList_Size());
                    resetColor();
                } else if (confirmResult == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(this, "Ban da huy bo them moi");
                }

            }
        }

    }//GEN-LAST:event_btn_ThemMouseClicked

    private void btn_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateMouseClicked

        if (t == 1) {
            StringBuilder stb = new StringBuilder();
            int pos = tblThuocTinh.getSelectedRow();
            if (!v.isEmpty(txtThuocTinh, "Vui long nhap ten thuoc tinh muon them", stb)) {
                JOptionPane.showMessageDialog(this, stb);
            } else {
                int confirmResult = JOptionPane.showConfirmDialog(this, "Ban co chac chan muon them khong?", "Xac nhan", JOptionPane.YES_NO_OPTION);
                if (confirmResult == JOptionPane.YES_OPTION) {
                    int maDanhMuc = tts.getList_DanhMuc().get(pos).getMaThuocTinh();
                    String kq = tts.Update_DanhMuc(getModel(), maDanhMuc);
                    JOptionPane.showMessageDialog(this, kq);
                    loadDataDanhMuc(tts.getList_DanhMuc());
                    resetColor();
                } else if (confirmResult == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(this, "Ban da huy bo them moi");
                }

            }
        }

        if (t == 2) {
            StringBuilder stb = new StringBuilder();
            int pos = tblThuocTinh.getSelectedRow();
            if (!v.isEmpty(txtThuocTinh, "Vui long nhap ten thuoc tinh muon them", stb)) {
                JOptionPane.showMessageDialog(this, stb);
            } else {
                int confirmResult = JOptionPane.showConfirmDialog(this, "Ban co chac chan muon them khong?", "Xac nhan", JOptionPane.YES_NO_OPTION);
                if (confirmResult == JOptionPane.YES_OPTION) {
                    int maMau = tts.getList_Mau().get(pos).getMaThuocTinh();
                    String kq = tts.Update_Mau(getModel(), maMau);
                    JOptionPane.showMessageDialog(this, kq);
                    loadDataColor(tts.getList_Mau());
                    resetColor();
                } else if (confirmResult == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(this, "Ban da huy bo them moi");
                }

            }
        }

        if (t == 3) {
            StringBuilder stb = new StringBuilder();
            int pos = tblThuocTinh.getSelectedRow();
            if (!v.isEmpty(txtThuocTinh, "Vui long nhap ten thuoc tinh muon them", stb)) {
                JOptionPane.showMessageDialog(this, stb);
            } else {
                int confirmResult = JOptionPane.showConfirmDialog(this, "Ban co chac chan muon them khong?", "Xac nhan", JOptionPane.YES_NO_OPTION);
                if (confirmResult == JOptionPane.YES_OPTION) {
                    int maSize = tts.getList_Size().get(pos).getMaThuocTinh();
                    String kq = tts.Update_Size(getModel(), maSize);
                    JOptionPane.showMessageDialog(this, kq);
                    loadDataSize(tts.getList_Size());
                    resetColor();
                } else if (confirmResult == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(this, "Ban da huy bo them moi");
                }

            }
        }
    }//GEN-LAST:event_btn_UpdateMouseClicked

    private void btn_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DeleteMouseClicked

        if (t == 1) {
            StringBuilder stb = new StringBuilder();
            int pos = tblThuocTinh.getSelectedRow();
            if (!v.isEmpty(txtThuocTinh, "Vui long nhap ten thuoc tinh muon them", stb)) {
                JOptionPane.showMessageDialog(this, stb);
            } else {
                int confirmResult = JOptionPane.showConfirmDialog(this, "Ban co chac chan muon xoa khong?", "Xac nhan", JOptionPane.YES_NO_OPTION);
                if (confirmResult == JOptionPane.YES_OPTION) {
                    int maDanhMuc = tts.getList_DanhMuc().get(pos).getMaThuocTinh();
                    String kq = tts.Xoa_DanhMuc(maDanhMuc);
                    JOptionPane.showMessageDialog(this, kq);
                    loadDataDanhMuc(tts.getList_DanhMuc());
                    resetColor();
                } else if (confirmResult == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(this, "Ban da huy bo xoa bo");
                }
            }
        }

        if (t == 2) {
            StringBuilder stb = new StringBuilder();
            int pos = tblThuocTinh.getSelectedRow();
            if (!v.isEmpty(txtThuocTinh, "Vui long nhap ten thuoc tinh muon them", stb)) {
                JOptionPane.showMessageDialog(this, stb);
            } else {
                int confirmResult = JOptionPane.showConfirmDialog(this, "Ban co chac chan muon xoa khong?", "Xac nhan", JOptionPane.YES_NO_OPTION);
                if (confirmResult == JOptionPane.YES_OPTION) {
                    int maMau = tts.getList_Mau().get(pos).getMaThuocTinh();
                    String kq = tts.Xoa_Mau(maMau);
                    JOptionPane.showMessageDialog(this, kq);
                    loadDataColor(tts.getList_Mau());
                    resetColor();
                } else if (confirmResult == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(this, "Ban da huy bo xoa bo");
                }
            }
        }

        if (t == 3) {
            StringBuilder stb = new StringBuilder();
            int pos = tblThuocTinh.getSelectedRow();
            if (!v.isEmpty(txtThuocTinh, "Vui long nhap ten thuoc tinh muon them", stb)) {
                JOptionPane.showMessageDialog(this, stb);
            } else {
                int confirmResult = JOptionPane.showConfirmDialog(this, "Ban co chac chan muon xoa khong?", "Xac nhan", JOptionPane.YES_NO_OPTION);
                if (confirmResult == JOptionPane.YES_OPTION) {
                    int maSize = tts.getList_Size().get(pos).getMaThuocTinh();
                    String kq = tts.Xoa_Size(maSize);
                    JOptionPane.showMessageDialog(this, kq);
                    loadDataSize(tts.getList_Size());
                    resetColor();
                } else if (confirmResult == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(this, "Ban da huy bo xoa bo");
                }
            }
        }
    }//GEN-LAST:event_btn_DeleteMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThuocTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThuocTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThuocTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThuocTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThuocTinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblThuocTinh;
    private javax.swing.JTextField txtThuocTinh;
    // End of variables declaration//GEN-END:variables
}
